repos:
- repo: local
  hooks:
    - id: black
      name: "Checking formatting"
      entry: black --check .
      language: system
      types: [python]
      pass_filenames: false
      repos:
        - repo: https://github.com/psf/black
          rev: 21.12b0
          hooks:
            - id: black

    - id: isort
      name: "Checking imports"
      entry: isort --check-only .
      language: system
      types: [python]
      pass_filenames: false


    - id: flake8
      name: "Running linter"
      entry: flake8 .
      language: system
      types: [python]
      pass_filenames: false

